spring.application.name=backend-spring-boot
spring.datasource.url=jdbc:h2:./backend-spring-boot
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
spring.h2.console.enabled=true
